### ISSUE TITLE
deploying appliance takes a long, long time

### ISSUE THREAD

**Issue by jrudley** [Azure/azure-managedapp-samples#19]
How long does it normally take to provision the appliance? I am watching the logs and it has been 35 mins and nothing provisioned. The operation Write appliance was accepted, but no update. I am doing the sample 101 managed storage account into a west central us RG

**Comment by krnese** [comment]
If you go to the managed resource group to monitor the deployment of the Azure resources there, do you see anything?
We have a know issue where deployments might randomly hit error 500 - but eventually will retry to make the request.

**Comment by jrudley** [comment]
Just the operation Write appliance was accepted, but it never goes to Started.

**Comment by krnese** [comment]
That is logged in the resource group containing the managed app. Can you also check the resource group created with the "underlying" Azure resources, in the managed resource group?
If you have a correlation Id of the failed job, please share and I will have a look to see what's going on.

**Comment by krnese** [comment]
Closing this issue as I haven't heard back, and we've GA'd Service Catalog.

**Comment by jrudley** [comment]
Product/azure/some team at ms :)
