### ISSUE TITLE
Broken Link: Marketplace Managed Application at 101-managed-single-vm

### ISSUE THREAD

**Issue by sgireddy** [Azure/azure-managedapp-samples#38]
The following link for instructions to create Marketplace Managed Application is broken. 
Steps:
Navigate to: https://github.com/Azure/azure-managedapp-samples/tree/master/samples/101-managed-single-vm
Click "Marketplace Managed Application" in Readme.md.

**Comment by krnese** [comment]
Thanks. We'll pull this sample, and add another one shortly.

**Comment by sgireddy** [comment]
wow, it's closed, well done Mr. MS employee. Shortly means when? perhaps never. There has been a PR pending for months, fortunately I found the link working there.....
